"""create vendors table

Revision ID: 35a85e4426ad
Revises: 
Create Date: 2026-06-22 20:26:20.531724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '35a85e4426ad'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vendors',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.Text(), nullable=True),
    sa.Column('state', sa.Text(), nullable=True),
    sa.Column('lat', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('lng', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('mobile', sa.Text(), nullable=True),
    sa.Column('categories', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('occasions', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('payment_methods', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('capacity_min', sa.Integer(), nullable=True),
    sa.Column('capacity_max', sa.Integer(), nullable=True),
    sa.Column('price_veg_min', sa.Integer(), nullable=True),
    sa.Column('price_veg_max', sa.Integer(), nullable=True),
    sa.Column('price_nonveg_min', sa.Integer(), nullable=True),
    sa.Column('price_nonveg_max', sa.Integer(), nullable=True),
    sa.Column('image_urls', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('raw_description', sa.Text(), nullable=True),
    sa.Column('raw_faqs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ingested_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vendors')
    # ### end Alembic commands ###
