"""add slug

Revision ID: 9236042f1268
Revises: 35a85e4426ad
Create Date: 2026-06-23 10:10:18.532667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9236042f1268'
down_revision: Union[str, Sequence[str], None] = '35a85e4426ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendors', sa.Column('slug', sa.Text(), nullable=False))
    op.create_unique_constraint('uq_vendors_slug', 'vendors', ['slug'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_vendors_slug', 'vendors', type_='unique')
    op.drop_column('vendors', 'slug')
    # ### end Alembic commands ###
